import type { Metadata } from 'next'
import { Geist, Geist_Mono, Montserrat } from 'next/font/google'
import './global.css'
import Navbar from '@/components/global/navbar'

const displayFont = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
})

const bodyFont = Geist({
  variable: '--font-geist',
  subsets: ['latin'],
})

const monoFont = Geist_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodyFont.variable} ${monoFont.variable} ${displayFont.variable} font-sans text-white  bg-brand-primary antialiased bg-mint-500`}
      >
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
